// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {utils} from '../models';
import {main} from '../models';

export function CheckInitialized():Promise<boolean>;

export function DeletePassword(arg1:number):Promise<void>;

export function GetPasswordCounts():Promise<Record<string, number>>;

export function GetPasswordStrength(arg1:string):Promise<utils.PasswordStrength>;

export function IsUnlocked():Promise<boolean>;

export function Lock():Promise<void>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function QueryPasswords(arg1:string,arg2:string):Promise<Array<main.EntryVO>>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function SavePassword(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SearchPassword(arg1:string):Promise<Array<main.EntryVO>>;

export function SetupMasterPassword(arg1:string):Promise<void>;

export function ToggleFavorite(arg1:number):Promise<void>;

export function Unlock(arg1:string):Promise<void>;

export function UpdatePassword(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;
