// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeletePassword(arg1:number):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function QueryPasswords():Promise<Array<main.PasswordEntryVO>>;

export function Register(arg1:string,arg2:string):Promise<void>;

export function SavePassword(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SearchPassword(arg1:string):Promise<Array<main.PasswordEntryVO>>;

export function UpdatePassword(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;
