// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePassword(arg1) {
  return window['go']['main']['App']['DeletePassword'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function QueryPasswords() {
  return window['go']['main']['App']['QueryPasswords']();
}

export function Register(arg1, arg2) {
  return window['go']['main']['App']['Register'](arg1, arg2);
}

export function SavePassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePassword'](arg1, arg2, arg3);
}

export function SearchPassword(arg1) {
  return window['go']['main']['App']['SearchPassword'](arg1);
}

export function UpdatePassword(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdatePassword'](arg1, arg2, arg3, arg4);
}
